name: Unity Build (GameCI)

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build Windows Player
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache the Library folder to speed up subsequent builds
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('**/*.cs', 'Packages/manifest.json', 'ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-

      # Activate Unity with the license stored in the repository secrets
      - name: Activate Unity license
        uses: game-ci/unity-activate@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_VERSION: 6000.0.43f1

      # Build the project for Windows 64-bit
      - name: Build project
        id: build
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.0.43f1
          targetPlatform: StandaloneWindows64

      # Upload the generated build as a workflow artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsPlayer
          path: build/StandaloneWindows64 